name : advent_of_code
description : Puzzle solving of Advent of Code 2022 (visit https://adventofcode.com/2022)
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  test: ^1.20.0

